### ISSUE TITLE
needs tests

### ISSUE THREAD

**Issue by faiq** [Shrugs/partyparrot#1]

**Comment by dragonai** [comment]
+1

**Comment by devChuk** [comment]
Agreed

**Comment by dragonai** [comment]
![image](https://cloud.githubusercontent.com/assets/5124030/11139471/a5755996-899d-11e5-94aa-bea74e40c71f.png)

**Comment by mathur** [comment]
TTD

**Comment by Shrugs** [comment]
I actually added tests. You're welcome.
