### ISSUE TITLE
Slash command posting issue

### ISSUE THREAD

**Issue by brianroach** [Shrugs/partyparrot#14]
![image](https://cloud.githubusercontent.com/assets/9772694/18930024/46dcadb4-857b-11e6-8dcc-b7e54b8e4409.png)
For whatever reason the slash command is only 'party-parroting' the first letter of each word. Any idea why?

**Comment by Shrugs** [comment]
@brianroach ah, you'll have to add `:rightparrot:`, `:middleparrot:` and `:boredparrot:` as emojis to your slack; grab the emojis at http://cultofthepartyparrot.com and add them to your slack and you'll be good to go!

**Comment by brianroach** [comment]
You're a genius! 😊
