### ISSUE TITLE
In the Compact Slack theme, the first line of parrots gets shifted

### ISSUE THREAD

**Issue by m4olivei** [Shrugs/partyparrot#17]
When you have the Compact theme set (Preferences > Messages & Media > Message Theme > Compact), the first line of parrots is inline with the user name, causing it to shift away from the rest of the message.

Would it be possible to throw in a newline at the beginning?

![franz 2017-07-28 08-44-35](https://user-images.githubusercontent.com/191049/28717828-5456f4ce-7371-11e7-9d51-57656e66c70c.png)

**Comment by Shrugs** [comment]
Closed by #19

**Comment by Shrugs** [comment]
Thanks for the report/fix!
