### ISSUE TITLE
Add gitignore

### ISSUE THREAD

**Issue by mathur** [Shrugs/partyparrot#2]
The pyc is making my eyes bleed

:partyparrot2::partyparrot2::partyparrot2::partyparrot2:        
:partyparrot2:                        :partyparrot2:
:partyparrot2::partyparrot2::partyparrot2::partyparrot2:        
:partyparrot2:                                
:partyparrot2:                                

:partyparrot2:                        :partyparrot2:
:partyparrot2:                        :partyparrot2:
        :partyparrot2::partyparrot2::partyparrot2:        
                :partyparrot2:                
                :partyparrot2:                

        :partyparrot4::partyparrot4::partyparrot4::partyparrot4:
:partyparrot4:                                
:partyparrot4:                                
:partyparrot4:                                
        :partyparrot4::partyparrot4::partyparrot4::partyparrot4:

**Comment by mathur** [comment]
wow that didn't work

**Comment by Shrugs** [comment]
Github is not a fan of this
