### ISSUE TITLE
For some reason it suffixs a number to the end of the letter which breaks the emoji

### ISSUE THREAD

**Issue by ecasilla** [Shrugs/partyparrot#6]
`python partyparrot.py "hi mom" | pbcopy`

:partyparrot:                        :partyparrot:
:partyparrot:                        :partyparrot:
:partyparrot::partyparrot::partyparrot::partyparrot::partyparrot:
:partyparrot:                        :partyparrot:
:partyparrot:                        :partyparrot:

:partyparrot2:                                
:partyparrot2:                                
:partyparrot2:                                
:partyparrot2:                                
:partyparrot2:                                

:partyparrot4:                        :partyparrot4:
:partyparrot4::partyparrot4:        :partyparrot4::partyparrot4:
:partyparrot4:        :partyparrot4:        :partyparrot4:
:partyparrot4:                        :partyparrot4:
:partyparrot4:                        :partyparrot4:

        :partyparrot::partyparrot::partyparrot:        
:partyparrot:                        :partyparrot:
:partyparrot:                        :partyparrot:
:partyparrot:                        :partyparrot:
        :partyparrot::partyparrot::partyparrot:        

:partyparrot2:                        :partyparrot2:
:partyparrot2::partyparrot2:        :partyparrot2::partyparrot2:
:partyparrot2:        :partyparrot2:        :partyparrot2:
:partyparrot2:                        :partyparrot2:
:partyparrot2:                        :partyparrot2:

**Comment by Shrugs** [comment]
The default emoji set that it uses is `:partyparrot:`, `:partyparrot2:` and so on. To change the emoji set, use something like:

```
python partyparrot.py "hi mom" -e ":partyparrot:" ":my_custom_emoji:" ":my_other_emoji:" | pbcopy
```

and it will cycle through those emojis for each letter.

I think I'll change the defaults, though, to correspond with the values from http://cultofthepartyparrot.com/
