### ISSUE TITLE
Incompatible with python 3

### ISSUE THREAD

**Issue by kaeawc** [Shrugs/partyparrot#7]
Running python3 partyparrot.py:

```
Traceback (most recent call last):
  File "partyparrot.py", line 69, in <module>
    force=args.force
  File "partyparrot.py", line 51, in convert_str_to_emoji
    output_string += arr_to_str(c, emoji_iterator.next(), space)
AttributeError: 'itertools.cycle' object has no attribute 'next'
```

http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html#next

**Comment by Shrugs** [comment]
Because I believe the party parrot is important in everyone's daily life, I have fixed this egregious issue as soon as possible. Please enjoy the party parrot at your earliest convenience.
